# This is a basic workflow to help you get started with Actions

name: hexo-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout hexo-blog
        uses: actions/checkout@v2
        with:
          repository: vksir/hexo-blog
          path: hexo-blog

      - name: nodejs install
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: hexo install
        run: |
          npm install hexo-cli -g
          npm install

      - name: checkout hexo-theme-next
        uses: actions/checkout@v2
        with:
          repository: vksir/hexo-theme-next
          path: hexo-theme-next

      - name: checkout blog-posts
        uses: actions/checkout@v2
        with:
          repository: vksir/blog-posts
          path: blog-posts

      - name: set deploy private key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: organize repos
        run: |
          mkdir -p ~/hexo-blog
          mv hexo-blog ~/hexo-blog
          mkdir -p ~/hexo-blog/themes/hexo-theme-next
          mv hexo-theme-next ~/hexo-blog/themes/hexo-theme-next
          mkdir -p ~/hexo-blog/source/_posts/posts
          mv blog-posts/posts ~/hexo-blog/source/_posts/posts

      - name: hexo deploy
        run: |
          cd ~/hexo-blog
          hexo g -f -d

      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
